name: dsc_platform
description: A new Flutter application.

publish_to: 'play.google.com' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  bloc: ">=6.0.3 <7.0.0"
  flutter_bloc: ">=6.0.6 < 7.0.0"
  get_it: ">=5.0.1 <5.2.0"
  dio: ">=3.0.10 <3.1.0"
  cached_network_image: ">=2.3.2+1 <2.4.0"
  image_picker: ">=0.6.7+11 <0.7.0"
  image_cropper: ">=1.3.1 <1.4.0"
  meta: ">=1.2.3 <1.2.4"
  equatable: ">=1.2.5 <1.3.0"
  dartz: ">=0.9.2 <1.0.0"
  sqflite: ">=1.3.1+1 <1.4.0"
  zefyr: ">=0.12.0 <1.0.0"
  data_connection_checker: ">=0.3.4 <0.4.0"
  url_launcher: ">=5.7.2 <5.8.0"
  flushbar: ">=1.10.4 <1.11.0"
  flutter_svg: ">=0.19.0 <0.20.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ">=7.0.6 <8.0.0"
  mockito: ">= 4.1.1 <4.2.0"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
